### ISSUE TITLE
Make drills configurable

### ISSUE THREAD

**Issue by agourlay** [qdrant/coach#4]
The CLI currently enables to configure the coach engine and not each drill separately.

This means, the drilsl parameters are hardcoded for now which is not flexible.

It would be great to enable the configuration of the drills via a file.

For instance.

```yaml
drills:
 high_concurrency:
   concurrency_level: 250
   number_iterations: 1000
```
